### ISSUE TITLE
Measures in statistic 99910 "Regionalatlas Deutschland" have measures as dimensions

### ISSUE THREAD

**Issue by crijke** [datenguide/genesapi-tabular#3]
Several measures of statistic 99910 recursively have measures as dimension values: 

Measure AI_Z08, AI_Z09, AI_Z10,AI_Z11,AI_Z12,AI_Z13 and AI_Z14 all have measures AI_Z08, AI_Z09, AI_Z10,AI_Z11,AI_Z12,AI_Z13,AI_Z14 recursively listed as dimensions

Accoring to GENESIS Regionalatlas doesn't have any dimensions

**Comment by simonwoerpel** [comment]
is fixed via this: https://github.com/datenguide/genesapi-cli/commit/19a16d89774515a844748c5cd8fce379b8eafe22

example: https://docs.genesapi.org/99910/AI_Z07
