### ISSUE TITLE
Difference between GENESIS and tabular API schema

### ISSUE THREAD

**Issue by crijke** [datenguide/genesapi-tabular#4]
The following measures are present in regionalstatistik.de but not in the json schema (many of them from Regionalatlas). Are we maybe not using the latest version of the GENESIS schema? 

AENW01
AENW02
AENW03
AENW04
AENW05
AENW06
AEW002
AEW010
AI-Z01
AI-Z02
AI-Z03
AI-Z04
AI-Z05
AI-Z06
AI-Z07
AI-Z08
AI-Z09
AI-Z10
AI-Z11
AI-Z12
AI-Z13
AI-Z14
AI-Z15
AI-Z16
AI-Z17
AI-Z18
AI-Z19
AI0101
AI0102
AI0103
AI0104
AI0105
AI0106
AI0107
AI0108
AI0109
AI0110
AI0111
AI0112
AI0113
AI0201
AI0202
AI0203
AI0204
AI0205
AI0206
AI0207
AI0208
AI0209
AI0210
AI0211
AI0212
AI0213
AI0214
AI0215
AI0216
AI0217
AI0218
AI0219
AI0220
AI0301
AI0302
AI0303
AI0304
AI0305
AI0306
AI0307
AI0308
AI0309
AI0310
AI0311
AI0312
AI0401
AI0402
AI0501
AI0502
AI0503
AI0504
AI0505
AI0506
AI0601
AI0602
AI0603
AI0604
AI0605
AI0606
AI0701
AI0702
AI0703
AI0704
AI0705
AI0706
AI0707
AI0708
AI0709
AI0710
AI0711
AI0712
AI0713
AI0801
AI0802
AI0803
AI0804
AI0805
AI0806
AI0807
AI0808
AI0809
AI0901
AI0902
AI0903
AI0904
AI1001
AI1002
AI1101
AI1201
AI1202
AI1301
AI1302
AI1303
AI1304
AI1305
AI1401
AI1402
AI1403
AI1404
AI1405
AI1501
AI1601
AI1602
AI1701
AI1702
AI1703
AI1704
AI1705
AI1706
AI1707
AI1708
AI1709
AI1710
AI1711
AI1712
AI1801
AI1901
AI1902
AI1903
AI1904
AI1905
AI1906
AI1907
AI1908
AI2001
AI2101
AI2102
AI2103
AI2104
AI2105
AI2106
AI2107
AI2201
AI2202
AI2203
AI2204
AI2205
AI2301
AI2302
AI2401
ARBST1
ARBST2
AUSNW2
AUSNW4
BAU017
BAU018
BETR08
BEV215
BIP002
BIP003
BIP004
BIPI02
BIPI03
BIPI04
BTR030
BTR034
BTR038
BWSI05
ENTGEL
ERW009
ERW046
ERWN09
ERWO09
ERWZ01
ERWZ03
ETG009
FLC001
FLC047
FLC049
FLCNW1
FLCNW9
GEBWOR
GES054
GES065
GEW002
KIN004
KIND02
KIND33
PEN071
PEN072
PEN079
PEN081
PEN082
PEN088
PEN091
PFL001
PFL003
PFL004
PFL005
PFL006
PFL007
PFL008
PFL009
PFL011
PFL012
PLZ005
RMENW9
SLD012
SLNW01
SLNW02
SLNW03
STENW1
STENW2
STENW3
STENW4
STENW5
STEU02
STEU03
STEU04
STEU05
STEU06
STEU07
STEU08
VBR005
VBR012
VBR017
VBR020
WAS002
WAS003
WAS005
WASNW0
WASNW5
WASNW6
WGS001

**Comment by lhehnke** [comment]
Not sure whether it helps, but these statistics are at least included in the meta data. datenguideR uses the following query to retrieve them from your GraphQL API:

`query { __type(name: "Region") {
     fields {
     name
     description
     args {
       name
       type {
         name
         ofType {
           name
           description
           enumValues {
             name
             description
           }
         }
       }
     }
   }
 }}`
